server:
  port: 8081
app:
  eureka-server: localhost
spring:
  application:
    name: api-gateway

  # Spring cloud configuration
  cloud.gateway:
    # Main service routes
    routes[0].id: main-service
    routes[0].uri: lb://main-service
    routes[0].predicates[0]: Path=/api/v1/category
    routes[0].filters[0]: SetPath=/category

    routes[1].uri: lb://main-service
    routes[1].predicates[0]: Path=/api/v1/quiz
    routes[1].filters[0]: SetPath=/quiz

    routes[2].uri: lb://main-service
    routes[2].predicates[0]: Path=/api/v1/question
    routes[2].filters[0]: SetPath=/question

    # Discover Server Route
    routes[3].id: discovery-server
    routes[3].uri: http://eureka:password@${app.eureka-server}:8761
    routes[3].predicates[0]: Path=/eureka/web
    routes[3].filters[0]: SetPath=/

    ## Discover Server Static Resources Route
    routes[4].id: discovery-server-static
    routes[4].uri: http://eureka:password@${app.eureka-server}:8761
    routes[4].predicates[0]: Path=/eureka/**

  # Oauth2 Resource Server
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/quiz-craft-auth

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@${app.eureka-server}:8761/eureka